#ifdef CONFIG_TOP
#include "proffieboard_config.h"
#define NUM_BLADES 1
#define NUM_BUTTONS 2
#define VOLUME 2200
const unsigned int maxLedsPerStrip = 144;
#define CLASH_THRESHOLD_G 3.0
#define ENABLE_AUDIO
#define ENABLE_MOTION
#define ENABLE_WS2811
#define ENABLE_SD
#define NO_COLOR_SWING
#define SAVED_PRESET
#endif

#ifdef CONFIG_PRESETS
Preset presets[] = {
{"Korriban_CFX", "tracks/swtor_korriban_hw2.wav",
StylePtr<InOutHelper<OnSpark<LocalizedClash<Lockup<Blast<AudioFlicker<Red,Rgb<120,0,0>>,DeepSkyBlue>,Pulsing<Gradient<AudioFlicker<Red,Rgb<120,0,0>>,AudioFlicker<Red,Rgb<120,0,0>>,BrownNoiseFlicker<White,Strobe<SteelBlue,White,50,1>,100>,AudioFlicker<Red,Rgb<120,0,0>>,AudioFlicker<Red,Rgb<120,0,0>>,AudioFlicker<Red,Rgb<120,0,0>>>,Gradient<AudioFlicker<Red,Rgb<120,0,0>>,AudioFlicker<Red,Rgb<120,0,0>>,BrownNoiseFlicker<White,Strobe<SteelBlue,White,50,1>,100>,AudioFlicker<Red,Rgb<120,0,0>>,AudioFlicker<Red,Rgb<120,0,0>>>,3500>,AudioFlicker<Red,White>>,White,80>,HumpFlicker<MistyRose,Red,60>,1600>,500,700>>(), "Korriban_CFX_SS"},


{"Violence", "tracks/swtor_darksidetheme1.wav",
StylePtr<InOutHelper<OnSpark<Blast<LocalizedClash<Lockup<Gradient<Pulsing<Tomato,PeachPuff,4000>,AudioFlicker<Red,Tomato>,AudioFlicker<Red,Tomato>,AudioFlicker<Red,Tomato>>,Pulsing<Gradient<Gradient<Pulsing<Tomato,PeachPuff,4000>,AudioFlicker<Red,Tomato>,AudioFlicker<Red,Tomato>,AudioFlicker<Red,Tomato>>,Strobe<White,BrownNoiseFlicker<Orange,White,100>,50,1>,Gradient<Pulsing<Tomato,PeachPuff,4000>,AudioFlicker<Red,Tomato>,AudioFlicker<Red,Tomato>,AudioFlicker<Red,Tomato>>,Gradient<Pulsing<Tomato,PeachPuff,4000>,AudioFlicker<Red,Tomato>,AudioFlicker<Red,Tomato>,AudioFlicker<Red,Tomato>>,Strobe<White,BrownNoiseFlicker<Orange,White,100>,50,1>,Gradient<Pulsing<Tomato,PeachPuff,4000>,AudioFlicker<Red,Tomato>,AudioFlicker<Red,Tomato>,AudioFlicker<Red,Tomato>>,Gradient<Pulsing<Tomato,PeachPuff,4000>,AudioFlicker<Red,Tomato>,AudioFlicker<Red,Tomato>,AudioFlicker<Red,Tomato>>>,Pulsing<Gradient<Gradient<Pulsing<Tomato,PeachPuff,4000>,AudioFlicker<Red,Tomato>,AudioFlicker<Red,Tomato>,AudioFlicker<Red,Tomato>>,Gradient<Pulsing<Tomato,PeachPuff,4000>,AudioFlicker<Red,Tomato>,AudioFlicker<Red,Tomato>,AudioFlicker<Red,Tomato>>,Strobe<White,BrownNoiseFlicker<Orange,White,100>,50,1>,Gradient<Pulsing<Tomato,PeachPuff,4000>,AudioFlicker<Red,Tomato>,AudioFlicker<Red,Tomato>,AudioFlicker<Red,Tomato>>,Strobe<White,BrownNoiseFlicker<Orange,White,100>,50,1>,Gradient<Pulsing<Tomato,PeachPuff,4000>,AudioFlicker<Red,Tomato>,AudioFlicker<Red,Tomato>,AudioFlicker<Red,Tomato>>,Strobe<White,BrownNoiseFlicker<Orange,White,100>,50,1>,Gradient<Pulsing<Tomato,PeachPuff,4000>,AudioFlicker<Red,Tomato>,AudioFlicker<Red,Tomato>,AudioFlicker<Red,Tomato>>>,Gradient<Gradient<Pulsing<Tomato,PeachPuff,4000>,AudioFlicker<Red,Tomato>,AudioFlicker<Red,Tomato>,AudioFlicker<Red,Tomato>>,Gradient<Pulsing<Tomato,PeachPuff,4000>,AudioFlicker<Red,Tomato>,AudioFlicker<Red,Tomato>,AudioFlicker<Red,Tomato>>,Strobe<White,BrownNoiseFlicker<Orange,White,100>,50,1>,Gradient<Pulsing<Tomato,PeachPuff,4000>,AudioFlicker<Red,Tomato>,AudioFlicker<Red,Tomato>,AudioFlicker<Red,Tomato>>,Gradient<Pulsing<Tomato,PeachPuff,4000>,AudioFlicker<Red,Tomato>,AudioFlicker<Red,Tomato>,AudioFlicker<Red,Tomato>>,Strobe<White,BrownNoiseFlicker<Orange,White,100>,50,1>,Gradient<Pulsing<Tomato,PeachPuff,4000>,AudioFlicker<Red,Tomato>,AudioFlicker<Red,Tomato>,AudioFlicker<Red,Tomato>>>,1500>,2000>,RandomPerLEDFlicker<Orange,White>>,White,75,70>,Yellow>,Gradient<GhostWhite,Orange>,1000>,200,500>>(),"Violence"},


{"Sith_02", "tracks/Malgus.wav",
StylePtr<InOutHelper<OnSpark<Blast<LocalizedClash<Lockup<Gradient<Pulsing<AudioFlicker<FloralWhite,LightSalmon>,AudioFlicker<GhostWhite,Tomato>,2500>,HumpFlicker<Red,Tomato,50>,HumpFlicker<Red,Tomato,50>>,Pulsing<Gradient<Gradient<Pulsing<AudioFlicker<FloralWhite,LightSalmon>,AudioFlicker<GhostWhite,Tomato>,2500>,HumpFlicker<Red,Tomato,50>,HumpFlicker<Red,Tomato,50>>,Strobe<White,BrownNoiseFlicker<Magenta,White,100>,50,1>,Gradient<Pulsing<AudioFlicker<FloralWhite,LightSalmon>,AudioFlicker<GhostWhite,Tomato>,2500>,HumpFlicker<Red,Tomato,50>,HumpFlicker<Red,Tomato,50>>,Gradient<Pulsing<AudioFlicker<FloralWhite,LightSalmon>,AudioFlicker<GhostWhite,Tomato>,2500>,HumpFlicker<Red,Tomato,50>,HumpFlicker<Red,Tomato,50>>,Strobe<White,BrownNoiseFlicker<Magenta,White,100>,50,1>,Gradient<Pulsing<AudioFlicker<FloralWhite,LightSalmon>,AudioFlicker<GhostWhite,Tomato>,2500>,HumpFlicker<Red,Tomato,50>,HumpFlicker<Red,Tomato,50>>,Gradient<Pulsing<AudioFlicker<FloralWhite,LightSalmon>,AudioFlicker<GhostWhite,Tomato>,2500>,HumpFlicker<Red,Tomato,50>,HumpFlicker<Red,Tomato,50>>>,Pulsing<Gradient<Gradient<Pulsing<AudioFlicker<FloralWhite,LightSalmon>,AudioFlicker<GhostWhite,Tomato>,2500>,HumpFlicker<Red,Tomato,50>,HumpFlicker<Red,Tomato,50>>,Gradient<Pulsing<AudioFlicker<FloralWhite,LightSalmon>,AudioFlicker<GhostWhite,Tomato>,2500>,HumpFlicker<Red,Tomato,50>,HumpFlicker<Red,Tomato,50>>,Strobe<White,BrownNoiseFlicker<Magenta,White,100>,50,1>,Gradient<Pulsing<AudioFlicker<FloralWhite,LightSalmon>,AudioFlicker<GhostWhite,Tomato>,2500>,HumpFlicker<Red,Tomato,50>,HumpFlicker<Red,Tomato,50>>,Strobe<White,BrownNoiseFlicker<Magenta,White,100>,50,1>,Gradient<Pulsing<AudioFlicker<FloralWhite,LightSalmon>,AudioFlicker<GhostWhite,Tomato>,2500>,HumpFlicker<Red,Tomato,50>,HumpFlicker<Red,Tomato,50>>,Strobe<White,BrownNoiseFlicker<Magenta,White,100>,50,1>,Gradient<Pulsing<AudioFlicker<FloralWhite,LightSalmon>,AudioFlicker<GhostWhite,Tomato>,2500>,HumpFlicker<Red,Tomato,50>,HumpFlicker<Red,Tomato,50>>>,Gradient<Gradient<Pulsing<AudioFlicker<FloralWhite,LightSalmon>,AudioFlicker<GhostWhite,Tomato>,2500>,HumpFlicker<Red,Tomato,50>,HumpFlicker<Red,Tomato,50>>,Gradient<Pulsing<AudioFlicker<FloralWhite,LightSalmon>,AudioFlicker<GhostWhite,Tomato>,2500>,HumpFlicker<Red,Tomato,50>,HumpFlicker<Red,Tomato,50>>,Strobe<White,BrownNoiseFlicker<Magenta,White,100>,50,1>,Gradient<Pulsing<AudioFlicker<FloralWhite,LightSalmon>,AudioFlicker<GhostWhite,Tomato>,2500>,HumpFlicker<Red,Tomato,50>,HumpFlicker<Red,Tomato,50>>,Gradient<Pulsing<AudioFlicker<FloralWhite,LightSalmon>,AudioFlicker<GhostWhite,Tomato>,2500>,HumpFlicker<Red,Tomato,50>,HumpFlicker<Red,Tomato,50>>,Strobe<White,BrownNoiseFlicker<Magenta,White,100>,50,1>,Gradient<Pulsing<AudioFlicker<FloralWhite,LightSalmon>,AudioFlicker<GhostWhite,Tomato>,2500>,HumpFlicker<Red,Tomato,50>,HumpFlicker<Red,Tomato,50>>>,1500>,2000>,RandomPerLEDFlicker<Magenta,White>>,GhostWhite,100,65>,White>,White,800>,200,500>>(), "Sith_02"}, 


{"Ksith_The_Dark", "tracks/Dark_Deeds_SWTOR.wav",
StylePtr<InOutHelper<OnSpark<Blast<LocalizedClash<Lockup<Pulsing<RandomFlicker<Rgb16<34702,0,0>,Red>,Red,2500>,Pulsing<Gradient<Pulsing<RandomFlicker<Rgb16<34702,0,0>,Red>,Rgb16<34702,0,0>,2500>,Pulsing<RandomFlicker<Rgb16<34702,0,0>,Red>,Rgb16<34702,0,0>,2500>,Strobe<Green,BrownNoiseFlicker<Green,Red,100>,50,1>,Pulsing<RandomFlicker<Rgb16<34702,0,0>,Red>,Rgb16<34702,0,0>,2500>,Pulsing<RandomFlicker<Rgb16<34702,0,0>,Red>,Rgb16<34702,0,0>,2500>>,Gradient<Pulsing<RandomFlicker<Rgb16<34702,0,0>,Red>,Rgb16<34702,0,0>,2500>,Pulsing<RandomFlicker<Rgb16<34702,0,0>,Red>,Rgb16<34702,0,0>,2500>,Strobe<Green,BrownNoiseFlicker<Green,Red,100>,50,1>,Pulsing<RandomFlicker<Rgb16<34702,0,0>,Red>,Rgb16<34702,0,0>,2500>,Pulsing<RandomFlicker<Rgb16<34702,0,0>,Red>,Rgb16<34702,0,0>,2500>,Pulsing<RandomFlicker<Rgb16<34702,0,0>,Red>,Rgb16<34702,0,0>,2500>>,3500>,RandomPerLEDFlicker<Red,White>>,GreenYellow,120,75>,White>,MistyRose,1200>,200,500>>(), "KSith_The_Dark"},



{"BEspin_CFX", "tracks/Dark_Deeds_SWTOR.wav",
StylePtr<InOutHelper<OnSpark<Blast<LocalizedClash<Lockup<Rgb16<65535,0,0>,Pulsing<Gradient<Rgb16<65535,0,0>,Strobe<Yellow,BrownNoiseFlicker<Green,White,100>,50,1>,Rgb16<65535,0,0>,Rgb16<65535,0,0>,Strobe<Yellow,BrownNoiseFlicker<Green,White,100>,50,1>,Rgb16<65535,0,0>,Rgb16<65535,0,0>>,Pulsing<Gradient<Rgb16<65535,0,0>,Rgb16<65535,0,0>,Strobe<Yellow,BrownNoiseFlicker<Green,White,100>,50,1>,Rgb16<65535,0,0>,Strobe<Yellow,BrownNoiseFlicker<Green,White,100>,50,1>,Rgb16<65535,0,0>,Strobe<Yellow,BrownNoiseFlicker<Green,White,100>,50,1>,Rgb16<65535,0,0>>,Gradient<Rgb16<65535,0,0>,Rgb16<65535,0,0>,Strobe<Yellow,BrownNoiseFlicker<Green,White,100>,50,1>,Rgb16<65535,0,0>,Rgb16<65535,0,0>,Strobe<Yellow,BrownNoiseFlicker<Green,White,100>,50,1>,Rgb16<65535,0,0>>,1500>,2000>,RandomPerLEDFlicker<Red,White>>,Rgb<140,180,0>,120,70>,SpringGreen>,Rgb<140,180,0>,400>,200,500>>(), "BEspin_CFX"},



{"Control", "tracks/swtor_darksidetheme2.wav",
StylePtr<InOutHelper<OnSpark<OriginalBlast<LocalizedClash<Lockup<Gradient<Pulsing<Gradient<GhostWhite,DarkOrange>,Gradient<DarkOrange,Moccasin>,6000>,RandomFlicker<Orange,Yellow>,RandomFlicker<Orange,Yellow>>,Pulsing<Gradient<Gradient<Pulsing<Gradient<GhostWhite,DarkOrange>,Gradient<DarkOrange,Moccasin>,6000>,RandomFlicker<Orange,Yellow>,RandomFlicker<Orange,Yellow>>,Strobe<White,BrownNoiseFlicker<Red,White,100>,50,1>,Gradient<Pulsing<Gradient<GhostWhite,DarkOrange>,Gradient<DarkOrange,Moccasin>,6000>,RandomFlicker<Orange,Yellow>,RandomFlicker<Orange,Yellow>>,Gradient<Pulsing<Gradient<GhostWhite,DarkOrange>,Gradient<DarkOrange,Moccasin>,6000>,RandomFlicker<Orange,Yellow>,RandomFlicker<Orange,Yellow>>,Strobe<White,BrownNoiseFlicker<Red,White,100>,50,1>,Gradient<Pulsing<Gradient<GhostWhite,DarkOrange>,Gradient<DarkOrange,Moccasin>,6000>,RandomFlicker<Orange,Yellow>,RandomFlicker<Orange,Yellow>>,Gradient<Pulsing<Gradient<GhostWhite,DarkOrange>,Gradient<DarkOrange,Moccasin>,6000>,RandomFlicker<Orange,Yellow>,RandomFlicker<Orange,Yellow>>>,Pulsing<Gradient<Gradient<Pulsing<Gradient<GhostWhite,DarkOrange>,Gradient<DarkOrange,Moccasin>,6000>,RandomFlicker<Orange,Yellow>,RandomFlicker<Orange,Yellow>>,Gradient<Pulsing<Gradient<GhostWhite,DarkOrange>,Gradient<DarkOrange,Moccasin>,6000>,RandomFlicker<Orange,Yellow>,RandomFlicker<Orange,Yellow>>,Strobe<White,BrownNoiseFlicker<Red,White,100>,50,1>,Gradient<Pulsing<Gradient<GhostWhite,DarkOrange>,Gradient<DarkOrange,Moccasin>,6000>,RandomFlicker<Orange,Yellow>,RandomFlicker<Orange,Yellow>>,Strobe<White,BrownNoiseFlicker<Red,White,100>,50,1>,Gradient<Pulsing<Gradient<GhostWhite,DarkOrange>,Gradient<DarkOrange,Moccasin>,6000>,RandomFlicker<Orange,Yellow>,RandomFlicker<Orange,Yellow>>,Strobe<White,BrownNoiseFlicker<Red,White,100>,50,1>,Gradient<Pulsing<Gradient<GhostWhite,DarkOrange>,Gradient<DarkOrange,Moccasin>,6000>,RandomFlicker<Orange,Yellow>,RandomFlicker<Orange,Yellow>>>,Gradient<Gradient<Pulsing<Gradient<GhostWhite,DarkOrange>,Gradient<DarkOrange,Moccasin>,6000>,RandomFlicker<Orange,Yellow>,RandomFlicker<Orange,Yellow>>,Gradient<Pulsing<Gradient<GhostWhite,DarkOrange>,Gradient<DarkOrange,Moccasin>,6000>,RandomFlicker<Orange,Yellow>,RandomFlicker<Orange,Yellow>>,Strobe<White,BrownNoiseFlicker<Red,White,100>,50,1>,Gradient<Pulsing<Gradient<GhostWhite,DarkOrange>,Gradient<DarkOrange,Moccasin>,6000>,RandomFlicker<Orange,Yellow>,RandomFlicker<Orange,Yellow>>,Gradient<Pulsing<Gradient<GhostWhite,DarkOrange>,Gradient<DarkOrange,Moccasin>,6000>,RandomFlicker<Orange,Yellow>,RandomFlicker<Orange,Yellow>>,Strobe<White,BrownNoiseFlicker<Red,White,100>,50,1>,Gradient<Pulsing<Gradient<GhostWhite,DarkOrange>,Gradient<DarkOrange,Moccasin>,6000>,RandomFlicker<Orange,Yellow>,RandomFlicker<Orange,Yellow>>>,1500>,2000>,RandomPerLEDFlicker<Red,White>>,White,40,80>,White>,Gradient<GhostWhite,Yellow>,1000>,200,500>>(), "Control"},


{"Corellian_CFX", "tracks/swtor_korriban_hw1.wav",
StylePtr<InOutHelper<OnSpark<OriginalBlast<LocalizedClash<Lockup<RandomFlicker<Red,Rgb<170,0,0>>,Pulsing<Gradient<RandomFlicker<Red,Rgb<170,0,0>>,Strobe<White,BrownNoiseFlicker<Red,White,100>,50,1>,RandomFlicker<Red,Rgb<170,0,0>>,RandomFlicker<Red,Rgb<170,0,0>>,Strobe<White,BrownNoiseFlicker<Red,White,100>,50,1>,RandomFlicker<Red,Rgb<170,0,0>>,RandomFlicker<Red,Rgb<170,0,0>>>,Pulsing<Gradient<RandomFlicker<Red,Rgb<170,0,0>>,RandomFlicker<Red,Rgb<170,0,0>>,Strobe<White,BrownNoiseFlicker<Red,White,100>,50,1>,RandomFlicker<Red,Rgb<170,0,0>>,Strobe<White,BrownNoiseFlicker<Red,White,100>,50,1>,RandomFlicker<Red,Rgb<170,0,0>>,Strobe<White,BrownNoiseFlicker<Red,White,100>,50,1>,RandomFlicker<Red,Rgb<170,0,0>>>,Gradient<RandomFlicker<Red,Rgb<170,0,0>>,RandomFlicker<Red,Rgb<170,0,0>>,Strobe<White,BrownNoiseFlicker<Red,White,100>,50,1>,RandomFlicker<Red,Rgb<170,0,0>>,RandomFlicker<Red,Rgb<170,0,0>>,Strobe<White,BrownNoiseFlicker<Red,White,100>,50,1>,RandomFlicker<Red,Rgb<170,0,0>>>,1500>,2000>,RandomPerLEDFlicker<Red,White>>,White,100,85>,Green>,Gradient<GhostWhite,AudioFlicker<Orange,Yellow>>,1000>,200,500>>(), "Corellian"},



{ "Calibrate", "tracks/hum.wav",
    &style_charging, "Battery\nLevel"}
};
BladeConfig blades[] = {
 { 0, WS281XBladePtr<121, bladePin, Color8::GRB, PowerPINS<bladePowerPin2, bladePowerPin3> >(), CONFIGARRAY(presets) },
};
#endif

#ifdef CONFIG_BUTTONS
Button PowerButton(BUTTON_POWER, powerButtonPin, "pow");
Button AuxButton(BUTTON_AUX, auxPin, "aux");
#endif
